# Export traces to Honeycomb.
#
# Variables:
#
# - $HONEYCOMB_API_KEY
# - $HONEYCOMB_DATASET
#
# Learn more: https://docs.honeycomb.io/getting-data-in/otel-collector/

receivers:
  otlp:
    protocols:
      grpc: # port 4317
      http: # port 4318

exporters:
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "$HONEYCOMB_API_KEY"

processors:
  tail_sampling:
    decision_wait: 30s
    num_traces: 100000
    expected_new_traces_per_sec: 10 # We currently have about ~700k events per day
    policies:
      name: and
      type: and
      and:
        and_sub_policy:
          # Only track events that originate from the completion provider
          - name: is-completion-event
            type: ottl_condition
            ottl_condition:
              error_mode: ignore
              span:
                - "name == \"autocomplete.provideInlineCompletionItems\""
          # Only track spans that were manually marked as to be sampled by the client
          - name: is-sampled
            type: ottl_condition
            ottl_condition:
              error_mode: ignore
              span:
                - "attributes[\"sampled\"] == true"

extensions:
  health_check:
  zpages:
    endpoint: ":55679"

service:
  extensions: [health_check,zpages]
  pipelines:
    traces/autocomplete:
      processors:
        - tail_sampling
      receivers: [otlp]
      exporters: [otlp]
