name: Cody context filters tests change

on:
  pull_request_target:
    paths:
      - 'cmd/frontend/internal/codycontext/testdata/enterprise_filter_test_data.json'

permissions:
  issues: write

jobs:
  check-action:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a Message
        run: echo "The action has triggered successfully!"
